### ISSUE TITLE
Server side bug.

### ISSUE THREAD

**Issue by kstreee** [o-hoo/Around#28]
arounddev.azurewebsites.net/api/SearchAPI/Venues/?sw=25.025646,121.550795&ne=25.036465,121.564078&pagesize=12&page=1

```
Object reference not set to an instance of an object.
at AroundAPIServer.BizObjects.SearchEngine.Plugin.PhotoFirstPlugin.<PushBackNoPhotoVenues>b__0(Venue v)
at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
at System.Linq.Enumerable.<ConcatIterator>d__1`1.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
at System.Linq.Enumerable.<SkipIterator>d__1`1.MoveNext()
at System.Linq.Enumerable.<TakeIterator>d__1`1.MoveNext()
at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
at AroundAPIServer.BizObjects.SearchEngine.VenueSearcher.Search(SquareCoordinate squareCoordinate, String optionString, String optionString2, Int32 page, Int32 pageSize)
at AroundAPIServer.Controllers.API.SearchAPIController.<>c__DisplayClass7.<Venues>b__6()
at AroundAPIServer.Models.Common.HTTPAPIResponse`1.Build(Func`1 predicate)"
```

**Comment by kstreee** [comment]
@modamoda 
Add test cases (?)
https://github.com/kstreee-around/AroundServer/commit/b96feea4a282131364f297dfd8988cdd9dfa3628
